### ISSUE TITLE
Single Modality Style Transfer Results for Videos

### ISSUE THREAD

**Issue by Alibabade** [NevSNev/UniST#4]
Hi, great works!! 
I'd like to reproduce the consistent stylized results for a video (MPI Sintel Sence 3), but no luck (a little sad). I run the script application/single_modality/video/inference_video.py with replacements of test_options.py under the same directory and image_datasets.py at the directory application/single_modality. It works fine and outputs results, but the stylized frames are not consistent, could you please help to tell if I made something wrong?

And could you also please tell me that, is it possible to keep the frame resolution at the original one like 1024x436?

Many thanks!!

**Comment by NevSNev** [comment]
Well, according to your description, i think you probably forget to change the Model.py. Please refer to the  corresponding README. As for the resolution you can resize it after you have the results.
